// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Dashboard {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    Title: string;
    Subtitle?: string;
    Images: { data: Media[] };
  };
}
export interface Dashboard_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Title: string;
  Subtitle?: string;
  Images: Media[];
}

export interface Dashboard_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Title: string;
  Subtitle?: string;
  Images: number[];
}

export interface Dashboard_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Title: string;
  Subtitle?: string;
  Images: AdminPanelRelationPropertyModification<Media>[];
}
