// Interface automatically generated by schemas-to-ts

export interface ContactEmail {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    name: string;
    email: string;
    message: string;
  };
}
export interface ContactEmail_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  email: string;
  message: string;
}

export interface ContactEmail_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  email: string;
  message: string;
}

export interface ContactEmail_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  email: string;
  message: string;
}
