// Interface automatically generated by schemas-to-ts

export interface Links {
  name: string;
  url: string;
  icon?: string;
}
export interface Links_Plain {
  name: string;
  url: string;
  icon?: string;
}

export interface Links_NoRelations {
  name: string;
  url: string;
  icon?: string;
}

