// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Event {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    image: { data: Media };
    url?: string;
    name?: string;
    start_date?: Date;
    address?: string;
    end_date?: Date;
  };
}
export interface Event_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  image: Media;
  url?: string;
  name?: string;
  start_date?: Date;
  address?: string;
  end_date?: Date;
}

export interface Event_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  image: number;
  url?: string;
  name?: string;
  start_date?: Date;
  address?: string;
  end_date?: Date;
}

export interface Event_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  image: AdminPanelRelationPropertyModification<Media>;
  url?: string;
  name?: string;
  start_date?: Date;
  address?: string;
  end_date?: Date;
}
