// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { Category } from '../../../category/content-types/category/category';
import { Category_Plain } from '../../../category/content-types/category/category';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Product {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    name: string;
    image: { data: Media[] };
    price: number;
    categories?: { data: Category[] };
    description?: string;
    availability: boolean;
  };
}
export interface Product_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  image: Media[];
  price: number;
  categories?: Category_Plain[];
  description?: string;
  availability: boolean;
}

export interface Product_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  image: number[];
  price: number;
  categories?: number[];
  description?: string;
  availability: boolean;
}

export interface Product_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  image: AdminPanelRelationPropertyModification<Media>[];
  price: number;
  categories?: AdminPanelRelationPropertyModification<Category_Plain>;
  description?: string;
  availability: boolean;
}
