// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface DashboardImage {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    image: { data: Media };
  };
}
export interface DashboardImage_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  image: Media;
}

export interface DashboardImage_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  image: number;
}

export interface DashboardImage_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  image: AdminPanelRelationPropertyModification<Media>;
}
